perf: update streamline process

diff --git a/.github/workflows/pi_build.yml b/.github/workflows/pi_build.yml
--- a/.github/workflows/pi_build.yml
+++ b/.github/workflows/pi_build.yml
@@ -13,28 +13,29 @@ env:
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
 jobs:
-  configure-branch-name:
-    name: 'Configure Head Branch Name'
+  validate-branch-name:
+    name: 'Validate Head Branch Name'
     runs-on: ubuntu-latest
-    outputs:
-      gh_head_ref: ${{ steps.configure-branch-name.outputs.gh_head_ref }}
     steps:
-      - name: Configure branch name
-        id: configure-branch-name
-        run: echo "gh_head_ref=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's|/|-|g')" >> $GITHUB_OUTPUT
+      - name: Validate branch name
+        run: |
+          if [ "${{ github.event.pull_request.head.ref }}" != "parent-image-updates" ]; then
+            echo "::error::Branch name must be 'parent-image-updates'. Current branch name: ${{ github.event.pull_request.head.ref }}"
+            exit 1
+          fi
 
   pi-matrix:
     uses: code-kern-ai/cicd-deployment-scripts/.github/workflows/pi_matrix.yml@dev
     secrets: inherit
-    needs: [configure-branch-name]
+    needs: [validate-branch-name]
     with:
-      checkout_ref: ${{ needs.configure-branch-name.outputs.gh_head_ref }}
+      checkout_ref: parent-image-updates
       repository: "${{ github.repository_owner }}/refinery-submodule-parent-images"
 
   pi-build:
     name: 'Parent Images: Docker Build'
     runs-on: ubuntu-latest
-    needs: [pi-matrix, configure-branch-name]
+    needs: [pi-matrix, validate-branch-name]
     environment: dev
     env:
       PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
@@ -43,8 +44,8 @@ jobs:
       DEV_LOGIN_PASSWORD: ${{ secrets.DEV_LOGIN_PASSWORD }}
       PARENT_IMAGE_NAME: ${{ vars.PARENT_IMAGE_NAME }}
       DOCKERFILE: ${{ vars.DOCKERFILE }}
-      HEAD_REF: ${{ needs.configure-branch-name.outputs.gh_head_ref }}
-      IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || needs.configure-branch-name.outputs.gh_head_ref }}
+      HEAD_REF: parent-image-updates
+      IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || 'parent-image-updates' }}
     strategy:
       matrix:
         parent_image_type: ${{ fromJson(needs.pi-matrix.outputs.parent_image_type) }}
@@ -120,7 +121,7 @@ jobs:
   pi-update-app:
     name: 'Parent Images: App'
     runs-on: ubuntu-latest
-    needs: [pi-matrix, pi-build, configure-branch-name]
+    needs: [pi-matrix, pi-build, validate-branch-name]
     environment: dev
     continue-on-error: true
     env:
@@ -128,7 +129,7 @@ jobs:
       DOCKERHUB_CONTAINER_REGISTRY: ${{ vars.DOCKERHUB_CONTAINER_REGISTRY }}
       PARENT_IMAGE_NAME: ${{ vars.PARENT_IMAGE_NAME }}
       DOCKERFILE: ${{ vars.DOCKERFILE }}
-      HEAD_REF: ${{ needs.configure-branch-name.outputs.gh_head_ref }}
+      HEAD_REF: parent-image-updates
     strategy:
       matrix: 
         app: ${{ fromJson(needs.pi-matrix.outputs.app) }}
diff --git a/.github/workflows/pi_merge_parent_image.yml b/.github/workflows/pi_merge_parent_image.yml
--- a/.github/workflows/pi_merge_parent_image.yml
+++ b/.github/workflows/pi_merge_parent_image.yml
@@ -13,13 +13,13 @@ env:
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
 jobs:
-  pi-matrix:
-    uses: code-kern-ai/cicd-deployment-scripts/.github/workflows/pi_matrix.yml@dev
-    secrets: inherit
-    with:
-      checkout_ref: ${{ github.event.pull_request.base.ref }}
-      repository: "${{ github.repository_owner }}/refinery-submodule-parent-images"
-      parent_image_type: ${{ vars.PARENT_IMAGE_TYPE }}
+  # pi-matrix:
+  #   uses: code-kern-ai/cicd-deployment-scripts/.github/workflows/pi_matrix.yml@dev
+  #   secrets: inherit
+  #   with:
+  #     checkout_ref: ${{ github.event.pull_request.base.ref }}
+  #     repository: "${{ github.repository_owner }}/refinery-submodule-parent-images"
+  #     parent_image_type: ${{ vars.PARENT_IMAGE_TYPE }}
 
   pi-build:
     name: 'Parent Images: Docker Build'
@@ -47,10 +47,10 @@ jobs:
       - name: Install Dependencies
         run: python -m pip install pip-tools
       
-      - name: Compile Requirements
-        run: |
-          cd ${{ github.workspace }}/submodules/parent-images
-          pip-compile requirements/${{ env.PARENT_IMAGE_TYPE }}-requirements.in
+      # - name: Compile Requirements
+      #   run: |
+      #     cd ${{ github.workspace }}/submodules/parent-images
+      #     pip-compile requirements/${{ env.PARENT_IMAGE_TYPE }}-requirements.in
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -127,108 +127,108 @@ jobs:
       #       platform=linux/arm64
       #       label=dockerfile-path=https://github.com/refinery-${{ env.PARENT_IMAGE_TYPE }}-parent-image/blob/${{ github.sha }}/Dockerfile
 
-  pi-update-app:
-    name: 'Parent Images: App'
-    runs-on: ubuntu-latest
-    needs: [pi-matrix, pi-build]
-    environment: dev
-    continue-on-error: true
-    env:
-      PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
-      HEAD_REF: parent-image-updates
-    strategy:
-      matrix: 
-        include: ${{ fromJson(needs.pi-matrix.outputs.include) }}
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          submodules: 'true'
+  # pi-update-app:
+  #   name: 'Parent Images: App'
+  #   runs-on: ubuntu-latest
+  #   needs: [pi-matrix, pi-build]
+  #   environment: dev
+  #   continue-on-error: true
+  #   env:
+  #     PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
+  #     HEAD_REF: parent-image-updates
+  #   strategy:
+  #     matrix: 
+  #       include: ${{ fromJson(needs.pi-matrix.outputs.include) }}
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         submodules: 'true'
       
-      - name: Set up Python
-        if: matrix.parent_image_type != 'next'
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ env.PYTHON_VERSION }}
+  #     - name: Set up Python
+  #       if: matrix.parent_image_type != 'next'
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ env.PYTHON_VERSION }}
     
-      - name: Install Dependencies
-        if: matrix.parent_image_type != 'next'
-        run: python -m pip install pip-tools
+  #     - name: Install Dependencies
+  #       if: matrix.parent_image_type != 'next'
+  #       run: python -m pip install pip-tools
       
-      - name: Clone ${{ matrix.app }}
-        run: |
-          git clone --recurse-submodules https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ matrix.app }}.git
-          cd ${{ github.workspace }}/${{ matrix.app }}
+  #     - name: Clone ${{ matrix.app }}
+  #       run: |
+  #         git clone --recurse-submodules https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ matrix.app }}.git
+  #         cd ${{ github.workspace }}/${{ matrix.app }}
 
-          git config user.email "devtools@kern.ai"
-          git config user.name "GitHub Actions"
+  #         git config user.email "devtools@kern.ai"
+  #         git config user.name "GitHub Actions"
 
-          git checkout -b ${{ env.HEAD_REF }} || git checkout ${{ env.HEAD_REF }}
+  #         git checkout -b ${{ env.HEAD_REF }} || git checkout ${{ env.HEAD_REF }}
 
-      - name: Compile Requirements (Python)
-        if: matrix.parent_image_type != 'next'
-        run: |
-          pip-compile --quiet \
-            --output-file ${{ matrix.app }}/requirements/${{ matrix.parent_image_type }}-requirements.txt \
-            submodules/parent-images/requirements/${{ matrix.parent_image_type }}-requirements.in
+  #     - name: Compile Requirements (Python)
+  #       if: matrix.parent_image_type != 'next'
+  #       run: |
+  #         pip-compile --quiet \
+  #           --output-file ${{ matrix.app }}/requirements/${{ matrix.parent_image_type }}-requirements.txt \
+  #           submodules/parent-images/requirements/${{ matrix.parent_image_type }}-requirements.in
       
-      - name: Compile Requirements (Next)
-        if: matrix.parent_image_type == 'next'
-        run: |
-          jq --slurp '.[0] * .[1]' \
-            package.json \
-            ${{ matrix.app }}/package.json \
-            > package.json.tmp
-          mv package.json.tmp ${{ matrix.app }}/package.json
+  #     - name: Compile Requirements (Next)
+  #       if: matrix.parent_image_type == 'next'
+  #       run: |
+  #         jq --slurp '.[0] * .[1]' \
+  #           package.json \
+  #           ${{ matrix.app }}/package.json \
+  #           > package.json.tmp
+  #         mv package.json.tmp ${{ matrix.app }}/package.json
 
-      - name: Perform Edit/Git Operations (Python)
-        if: matrix.parent_image_type != 'next'
-        run: |
-          cd ${{ github.workspace }}/${{ matrix.app }}
+  #     - name: Perform Edit/Git Operations (Python)
+  #       if: matrix.parent_image_type != 'next'
+  #       run: |
+  #         cd ${{ github.workspace }}/${{ matrix.app }}
 
-          git add requirements/${{ matrix.parent_image_type }}-requirements.txt
-          git commit -m "ci: update ${{ matrix.parent_image_type }}-requirements.txt" || true
-          git push origin ${{ env.HEAD_REF }}
-          echo "::notice::${{ matrix.app }} - updated ${{ matrix.parent_image_type }}-requirements.txt"
+  #         git add requirements/${{ matrix.parent_image_type }}-requirements.txt
+  #         git commit -m "ci: update ${{ matrix.parent_image_type }}-requirements.txt" || true
+  #         git push origin ${{ env.HEAD_REF }}
+  #         echo "::notice::${{ matrix.app }} - updated ${{ matrix.parent_image_type }}-requirements.txt"
 
-          export exitcode=0
-          pip-compile --quiet \
-            --output-file requirements.txt \
-            requirements/requirements.in || export exitcode=$?
+  #         export exitcode=0
+  #         pip-compile --quiet \
+  #           --output-file requirements.txt \
+  #           requirements/requirements.in || export exitcode=$?
           
-          if [ $exitcode -ne 0 ]; then
-            echo "::error::pip-compile failed with exit code $exitcode"
-            exit $exitcode
-          else
-            git add requirements.txt
-            git commit -m "ci: update requirements.txt" || true
-            git push origin ${{ env.HEAD_REF }}
-            echo "::notice::${{ matrix.app }} - updated requirements.txt"
-          fi
+  #         if [ $exitcode -ne 0 ]; then
+  #           echo "::error::pip-compile failed with exit code $exitcode"
+  #           exit $exitcode
+  #         else
+  #           git add requirements.txt
+  #           git commit -m "ci: update requirements.txt" || true
+  #           git push origin ${{ env.HEAD_REF }}
+  #           echo "::notice::${{ matrix.app }} - updated requirements.txt"
+  #         fi
 
-          gh pr create --draft \
-            --title "${{ github.event.pull_request.title }}" \
-            --body "${{ github.event.pull_request.body }}" \
-            --base dev \
-            --head ${{ env.HEAD_REF }} \
-            --repo ${{ github.repository_owner }}/${{ matrix.app }} || true
+  #         gh pr create --draft \
+  #           --title "${{ github.event.pull_request.title }}" \
+  #           --body "${{ github.event.pull_request.body }}" \
+  #           --base dev \
+  #           --head ${{ env.HEAD_REF }} \
+  #           --repo ${{ github.repository_owner }}/${{ matrix.app }} || true
           
-      - name: Perform Edit/Git Operations (Next)
-        if: matrix.parent_image_type == 'next'
-        run: |
-          cd ${{ github.workspace }}/${{ matrix.app }}
+  #     - name: Perform Edit/Git Operations (Next)
+  #       if: matrix.parent_image_type == 'next'
+  #       run: |
+  #         cd ${{ github.workspace }}/${{ matrix.app }}
 
-          git add package.json
-          git commit -m "ci: update ${{ matrix.parent_image_type }} package.json" || true
-          git push origin ${{ env.HEAD_REF }}
-          echo "::notice::${{ matrix.app }} - updated ${{ matrix.parent_image_type }} package.json"
+  #         git add package.json
+  #         git commit -m "ci: update ${{ matrix.parent_image_type }} package.json" || true
+  #         git push origin ${{ env.HEAD_REF }}
+  #         echo "::notice::${{ matrix.app }} - updated ${{ matrix.parent_image_type }} package.json"
 
-          gh pr create --draft \
-            --title "${{ github.event.pull_request.title }}" \
-            --body "${{ github.event.pull_request.body }}" \
-            --base dev \
-            --head ${{ env.HEAD_REF }} \
-            --repo ${{ github.repository_owner }}/${{ matrix.app }} || true
+  #         gh pr create --draft \
+  #           --title "${{ github.event.pull_request.title }}" \
+  #           --body "${{ github.event.pull_request.body }}" \
+  #           --base dev \
+  #           --head ${{ env.HEAD_REF }} \
+  #           --repo ${{ github.repository_owner }}/${{ matrix.app }} || true
 
   gh-delete-branch:
     name: 'GitHub: Delete Branch'
diff --git a/.github/workflows/pi_merge_submodule.yml b/.github/workflows/pi_merge_submodule.yml
--- a/.github/workflows/pi_merge_submodule.yml
+++ b/.github/workflows/pi_merge_submodule.yml
@@ -99,21 +99,21 @@ jobs:
         shell: bash
         run: git push origin --delete ${{ github.event.pull_request.head.ref }}
 
-  gh-delete-app-branches:
-    name: 'GitHub: Delete App Branch'
-    needs: [configure-branch-name, pi-matrix, gh-delete-submodule-branches]
-    if: ${{ !failure() }}
-    runs-on: ubuntu-latest
-    strategy:
-      matrix: 
-        include: ${{ fromJson(needs.pi-matrix.outputs.include) }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GH_TOKEN }}
-          repository: ${{ github.repository_owner }}/${{ matrix.app }}
+  # gh-delete-app-branches:
+  #   name: 'GitHub: Delete App Branch'
+  #   needs: [configure-branch-name, pi-matrix, gh-delete-submodule-branches]
+  #   if: ${{ !failure() }}
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix: 
+  #       include: ${{ fromJson(needs.pi-matrix.outputs.include) }}
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
+  #         repository: ${{ github.repository_owner }}/${{ matrix.app }}
 
-      - name: Delete Branch
-        shell: bash
-        run: git push origin --delete ${{ needs.configure-branch-name.outputs.gh_head_ref }} || true
+  #     - name: Delete Branch
+  #       shell: bash
+  #       run: git push origin --delete ${{ needs.configure-branch-name.outputs.gh_head_ref }} || true
