perf: apply testing changes to app repos

diff --git a/.github/workflows/pi_build.yml b/.github/workflows/pi_build.yml
--- a/.github/workflows/pi_build.yml
+++ b/.github/workflows/pi_build.yml
@@ -41,6 +41,9 @@ jobs:
       DEV_CONTAINER_REGISTRY: ${{ vars.DEV_CONTAINER_REGISTRY }}
       DEV_LOGIN_USERNAME: ${{ secrets.DEV_LOGIN_USERNAME }}
       DEV_LOGIN_PASSWORD: ${{ secrets.DEV_LOGIN_PASSWORD }}
+      PARENT_IMAGE_NAME: ${{ vars.PARENT_IMAGE_NAME }}
+      DOCKERFILE: ${{ vars.DOCKERFILE }}
+      HEAD_REF: ${{ needs.configure-branch-name.outputs.gh_head_ref }}
       IMAGE_TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || needs.configure-branch-name.outputs.gh_head_ref }}
     strategy:
       matrix:
@@ -65,7 +68,7 @@ jobs:
       - name: Compile Requirements
         run: |
           cd ${{ github.workspace }}/submodules/parent-images
-          git checkout ${{ needs.configure-branch-name.outputs.gh_head_ref }}
+          git checkout ${{ env.HEAD_REF }}
           pip-compile requirements/${{ matrix.parent_image_type }}-requirements.in
 
       - name: Set up Docker Buildx
@@ -85,30 +88,158 @@ jobs:
           username: "${{ env.DEV_LOGIN_USERNAME }}"
           password: "${{ env.DEV_LOGIN_PASSWORD }}"
 
-      - name: Build & Push refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}
+      - name: Build & Push ${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}
         uses: docker/build-push-action@v5
         with:
           context: .
-          cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}-cache
-          cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}-cache,mode=max,image-manifest=true
+          cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}-cache
+          cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}-cache,mode=max,image-manifest=true
           platforms: linux/amd64
-          file: Dockerfile
-          tags: ${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}
+          file: ${{ env.DOCKERFILE }}
+          tags: ${{ env.DEV_CONTAINER_REGISTRY }}/${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}
           push: true
           build-args: |
             platform=linux/amd64
-            label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/Dockerfile
+            label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/${{ env.DOCKERFILE }}
 
-      - name: Build & Push refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}-arm64
+      - name: Build & Push ${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}-arm64
         uses: docker/build-push-action@v5
         with:
           context: .
-          cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}-arm64-cache
-          cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}-arm64-cache,mode=max,image-manifest=true
+          cache-from: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}-arm64-cache
+          cache-to: type=registry,ref=${{ env.DEV_CONTAINER_REGISTRY }}/${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}-arm64-cache,mode=max,image-manifest=true
           platforms: linux/arm64
-          file: Dockerfile
-          tags: ${{ env.DEV_CONTAINER_REGISTRY }}/refinery-parent-images:${{ needs.configure-branch-name.outputs.gh_head_ref }}-${{ matrix.parent_image_type }}-arm64
+          file: ${{ env.DOCKERFILE }}
+          tags: ${{ env.DEV_CONTAINER_REGISTRY }}/${{ env.PARENT_IMAGE_NAME }}:${{ env.HEAD_REF }}-${{ matrix.parent_image_type }}-arm64
           push: true
           build-args: |
             platform=linux/arm64
-            label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/Dockerfile
+            label=dockerfile-path=https://github.com/refinery-${{ matrix.parent_image_type }}-parent-image/blob/${{ github.sha }}/${{ env.DOCKERFILE }}
+
+  pi-update-app:
+    name: 'Parent Images: App'
+    runs-on: ubuntu-latest
+    needs: [pi-matrix, pi-build, configure-branch-name]
+    environment: dev
+    continue-on-error: true
+    env:
+      PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
+      DEV_CONTAINER_REGISTRY: ${{ vars.DEV_CONTAINER_REGISTRY }}
+      PARENT_IMAGE_NAME: ${{ vars.PARENT_IMAGE_NAME }}
+      DOCKERFILE: ${{ vars.DOCKERFILE }}
+      HEAD_REF: ${{ needs.configure-branch-name.outputs.gh_head_ref }}
+    strategy:
+      matrix: 
+        include: ${{ fromJson(needs.pi-matrix.outputs.include) }}
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          submodules: 'true'
+      
+      - name: Set up Python
+        if: matrix.parent_image_type != 'next'
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+    
+      - name: Install Dependencies
+        if: matrix.parent_image_type != 'next'
+        run: python -m pip install pip-tools
+      
+      - name: Clone cicd-deployment-scripts
+        run: git clone https://oauth2:${{ secrets.GH_TOKEN }}@github.com/code-kern-ai/cicd-deployment-scripts.git
+
+      - name: Clone ${{ matrix.app }}
+        run: |
+          git clone --recurse-submodules https://oauth2:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository_owner }}/${{ matrix.app }}.git
+          cd ${{ github.workspace }}/${{ matrix.app }}
+
+          git config user.email "devtools@kern.ai"
+          git config user.name "GitHub Actions"
+
+          git checkout -b ${{ env.HEAD_REF }} || git checkout ${{ env.HEAD_REF }}
+
+      - name: Compile Requirements (Python)
+        if: matrix.parent_image_type != 'next'
+        run: |
+          cd ${{ github.workspace }}/${{ matrix.app }}/submodules/parent-images
+          git checkout ${{ env.HEAD_REF }}
+          cd ${{ github.workspace }}/${{ matrix.app }}
+          pip-compile --quiet \
+            --output-file requirements/${{ matrix.parent_image_type }}-requirements.txt \
+            submodules/parent-images/requirements/${{ matrix.parent_image_type }}-requirements.in
+      
+      - name: Compile Requirements (Next)
+        if: matrix.parent_image_type == 'next'
+        run: |
+          cd ${{ github.workspace }}
+          jq --slurp '.[0] * .[1]' \
+            package.json \
+            ${{ matrix.app }}/package.json \
+            > package.json.tmp
+          mv package.json.tmp ${{ matrix.app }}/package.json
+
+      - name: Perform Edit/Git Operations (Python)
+        if: matrix.parent_image_type != 'next'
+        run: |
+          cd ${{ github.workspace }}/${{ matrix.app }}
+
+          bash ${{ github.workspace }}/cicd-deployment-scripts/pi/edit_dockerfile.sh \
+            -i "${{ env.PARENT_IMAGE_NAME }}" \
+            -t "${{ matrix.parent_image_type }}" \
+            -l "${{ env.HEAD_REF }}" \
+            -r "${{ env.DEV_CONTAINER_REGISTRY }}" \
+            -d "${{ env.DOCKERFILE }}"
+
+          git add requirements/${{ matrix.parent_image_type }}-requirements.txt
+          git commit -m "ci: update ${{ matrix.parent_image_type }}-requirements.txt" || true
+          git push origin ${{ env.HEAD_REF }}
+          echo "::notice::${{ matrix.app }} - updated ${{ matrix.parent_image_type }}-requirements.txt"
+
+          export exitcode=0
+          pip-compile --quiet \
+            --output-file requirements.txt \
+            requirements/requirements.in || export exitcode=$?
+          
+          if [ $exitcode -ne 0 ]; then
+            echo "::error::pip-compile failed with exit code $exitcode"
+            exit $exitcode
+          else
+            git add requirements.txt
+            git commit -m "ci: update requirements.txt" || true
+            git push origin ${{ env.HEAD_REF }}
+            echo "::notice::${{ matrix.app }} - updated requirements.txt"
+          fi
+
+          gh pr create --draft \
+            --title "${{ github.event.pull_request.title }}" \
+            --body "${{ github.event.pull_request.body }}" \
+            --base dev \
+            --head ${{ env.HEAD_REF }} \
+            --repo ${{ github.repository_owner }}/${{ matrix.app }} || true
+          
+      - name: Perform Edit/Git Operations (Next)
+        if: matrix.parent_image_type == 'next'
+        run: |
+          cd ${{ github.workspace }}/${{ matrix.app }}
+
+          bash ${{ github.workspace }}/cicd-deployment-scripts/pi/edit_dockerfile.sh \
+            -i "${{ env.PARENT_IMAGE_NAME }}" \
+            -t "${{ matrix.parent_image_type }}" \
+            -l "${{ env.HEAD_REF }}" \
+            -r "${{ env.DEV_CONTAINER_REGISTRY }}" \
+            -d "${{ env.DOCKERFILE }}"
+
+          git add package.json
+          git commit -m "ci: update ${{ matrix.parent_image_type }} package.json" || true
+          git push origin ${{ env.HEAD_REF }}
+          echo "::notice::${{ matrix.app }} - updated ${{ matrix.parent_image_type }} package.json"
+
+          gh pr create --draft \
+            --title "${{ github.event.pull_request.title }}" \
+            --body "${{ github.event.pull_request.body }}" \
+            --base dev \
+            --head ${{ env.HEAD_REF }} \
+            --repo ${{ github.repository_owner }}/${{ matrix.app }} || true
+          
